---
- name: Configure MPLS on P2
  hosts: P2
  gather_facts: false
  connection: local

  vars:
    cli:
      username: cisco
      password: cisco

  tasks:
    - name: configure MPLS on P2
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents:
          - interface FastEthernet0/0
        lines:
          - mpls ip

    - name: configure MPLS on P2
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents:
          - interface FastEthernet1/0
        lines:
          - mpls ip

